# Generated by Django 2.0 on 2018-08-21 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 9, 46, 11, 307138)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 9, 46, 11, 307138)),
        ),
    ]
